name: Test CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mac-aarch64-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Tag
      run: |
        git fetch --tags origin
        git push --delete next_macOS
        git tag next_macOS
        git push origin next_macOS
    - name: Build
      run: |
        echo "building"
    - name: Test
      run: echo "testing"
    - name: Package
      run: cp testfile.txt test.txt
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: macOS nightly build
        tag_name: next_macOS
        prerelease: true
        files: |
          test.tar
    
  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Tag
      run: |
        git fetch --tags origin
        git push --delete next_linux_x86_64
        git tag next_linux_x86_64
        git push origin next_linux_x86_64
    - name: Build
      run: |
        echo "building"
    - name: Test
      run: echo "testing"
    - name: Package
      run: cp testfile.txt test.txt
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: linux nightly build
        tag_name: next_linux_x86_64
        prerelease: true
        files: |
          test.txt
