name: Test CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  mac-aarch64-build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          echo "building"
    - name: Test
      run: echo "testing"
    - name: Package
      run: touch test.tar
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: macOS nightly build
        tag_name: next_macOS
        prerelease: true
        files: |
          test.tar
    
  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          echo "building"
    - name: Test
      run: echo "testing"
    - name: Package
      run: touch test.tar
    - name: Release
      uses: softprops/action-gh-release@v2.0.5
      with:
        name: linux nightly build
        tag_name: next_linux_x86_64
        prerelease: true
        files: |
          test.tar
