name: Bootstrap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mac-x86_64-build-bootstrap:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: fetch llvm-dev
      run: |
          brew update
          brew install llvm@17
          export PATH="/opt/homebrew/opt/llvm@17/bin:$PATH"
          lli --version
    - name: colgm-build
      run: |
          export PATH="/opt/homebrew/opt/llvm@17/bin:$PATH"
          cd test
          /opt/homebrew/opt/llvm@17/bin/clang out.ll -o colgm
          ./colgm main.colgm --lex --ast
          ./colgm lexer.colgm --lex --ast
    
  linux-x86_64-build-bootstrap:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: fetch llvm-dev
      run: |
          sudo apt-get update
          sudo apt-get install llvm-14-runtime llvm-14-dev
          export PATH="/usr/lib/llvm-14/bin:$PATH"
          lli --version
    - name: colgm-build
      run: |
          export PATH="/usr/lib/llvm-14/bin:$PATH"
          cd test
          /usr/lib/llvm-14/bin/clang out.ll -o colgm
          ./colgm main.colgm --lex --ast
          ./colgm lexer.colgm --lex --ast