name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mac-aarch64-build:
    runs-on: macos-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: fetch llvm-dev
      run: |
          brew update
          brew install llvm@17
          export PATH="/opt/homebrew/opt/llvm@17/bin:$PATH"
          lli --version
          ls /opt/homebrew/opt/llvm@17/bin
    - name: colgm-build
      run: |
          export PATH="/opt/homebrew/opt/llvm@17/bin:$PATH"
          cd test
          ls /opt/homebrew/opt/llvm@17/bin
          /opt/homebrew/opt/llvm@17/bin/clang out.ll -o colgm
          ./colgm
    - name: hello-build
      run: |
          mkdir cmake-build-mac
          cd cmake-build-mac
          cmake ../src -DCMAKE_BUILD_TYPE=Release
          make -j
          ./hello
    
  linux-x86_64-build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: fetch llvm-dev
      run: |
          sudo apt-get update
          sudo apt-get install llvm-14-runtime llvm-14-dev clang-14
          export PATH="/usr/lib/llvm-14/bin:$PATH"
          lli --version
          ls /usr/lib/llvm-14/bin
    - name: colgm-build
      run: |
          export PATH="/usr/lib/llvm-14/bin:$PATH"
          cd test
          ls /usr/lib/llvm-14/bin
          /usr/lib/llvm-14/bin/clang out.ll -o colgm
          /usr/bin/clang-14 out.ll -o colgm
          ./colgm
    - name: hello-build
      run: |
          mkdir cmake-build-linux
          cd cmake-build-linux
          cmake ../src -DCMAKE_BUILD_TYPE=Release
          make -j
          ./hello

  windows-x86_64-build-msvc:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: fetch llvm-dev
      run: |
          choco install -y llvm
          choco install -y cmake
    - name: verify
      run: clang --version
    - name: colgm-build
      run: |
          cd test
          clang out.ll -o colgm
          ./colgm
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
    - name: hello-build
      run: |
          mkdir cmake-build-windows-msvc
          cd cmake-build-windows-msvc
          cmake ../src -DCMAKE_BUILD_TYPE=Release
          MSBuild.exe hello.sln /p:Configuration=Release /p:Platform=x64
          .\Release\hello.exe

  windows-x86_64-build-mingw:
    runs-on: windows-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: fetch llvm-dev
      run: |
          choco install -y llvm
          choco install -y cmake
          choco install -y mingw
    - name: verify
      run: clang --version
    - name: colgm-build
      run: |
          cd test
          clang out.ll -o colgm
          ./colgm
    - name: hello-build
      run: |
          mkdir cmake-build-windows-mingw
          cd cmake-build-windows-mingw
          cmake -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++
          mingw32-make.exe -j6
          .\hello.exe